language: node_js

node_js:
  - "7.8"
  - "6.9"
  - "5.1"
  - "4.2"

before_script:
  - npm install

script:
  - npm test

notifications:
  emails:
    - tomk79@gmail.com
  on_success: always
  on_failure: always
