language: node_js

node_js:
  - "6.9"
  - "5.1"
  - "4.2"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-software-properties -qq
  - sudo add-apt-repository ppa:ondrej/php5-5.6 -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq php5 php5-sqlite
  - php -v
  - php -r "readfile('https://getcomposer.org/installer');" | php

before_script:
  - php composer.phar install
  - npm install

script:
  - npm test

notifications:
  emails:
    - tomk79@gmail.com
  on_success: always
  on_failure: always
