os:
  - linux

language: php

dist: trusty

php:
  - "8.1"
  - "8.0"
  - "7.4"
  - "7.3"


env:
  - NOTE_RELEASE=7.x

before_install:
  - composer selfupdate
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs

before_script:
  - composer install
  - npm install

script:
  - ./vendor/phpunit/phpunit/phpunit
  - npm run testcafe

notifications:
  emails:
    - tomk79@gmail.com
  on_success: always
  on_failure: always
