# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# Try out "interactive-mode"
os: Windows Server 2012 R2

# build version format
version: "{build}-{branch}"

# Set a known clone folder
clone_folder: C:\projects\myproject

# environments
environment:
  oauthtoken:
    secure: L7aFaHhJkScePf7T8vMrHn3xtwObmwfSjy36tXMOpb7qY8LXpSeieA6xx1oKiBk9
  matrix:
    - nodejs_version: "4.6"
    - nodejs_version: "5.12"
    - nodejs_version: "6.9"
    - nodejs_version: "7.8"

# branches
branches:
  only:
    - master
    - develop

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input
  - git config --global user.name "Tomoya Koyanagi"
  - git config --global user.email tomk79@gmail.com


# Install scripts
install:
  - cd C:\projects\myproject

  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install


# Post-install test scripts.
build_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test



test: off
deploy: off


notifications:
  # Email
  - provider: Email
    to:
      - tomk79@gmail.com
    on_build_status_changed: true
